version: "3"

services:
  webserver:
    image: "toothless:1"
    ports:
      - "80:80"
    volumes:
      - ./volume/php/fpm/:/etc/php/fpm
      - ./volume/php/cli/:/etc/php/cli
      - ./volume/openresty/nginx/conf:/usr/local/openresty/nginx/conf
      - ./volume/www:/www
      - ./volume/outbox:/land/outbox
